[package]
name = "pistontetris"
version = "0.1.0"
authors = ["gubbu <simonk55555@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
